[workspace]
members = ["crates/package", "crates/dnc", "xtask"]
resolver = "3"

[workspace.package]
version = "0.3.1"
edition = "2024"
authors = ["Peilin Fan <peilin.fan@foxmail.com>"]
description = "A shared Deno runtime for lightweight CLI and desktop application packages"
readme = "README.md"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.27.0"
zip = { version = "8.6.0", default-features = false, features = ["zstd"] }
dnr-package = { path = "crates/package" }

[profile.release]
lto = "thin"
strip = "debuginfo"
